#!/home/sean/.env/arc_env/bin/python
import random
import os
from arc import CLI

cli = CLI()

MESSAGES = [
    "Good luck out there!", "Have a nice day!", "Be the best you can be!",
    "Try your hardest!", "You can do great things!", "The possibilities are endless!"
]


@cli.script("anon", options=["message"], flags=["--sleep"])
def lock_anon(sleep, message=None):
    '''Locks the screen, but also accepts args
    :param message: message to display on the lock screen
    :flag sleep: determine whether or not to sleep after locking the machine
    '''
    if not message:
        message = random.choice(MESSAGES)

    flag = "-s" if sleep else "-l"

    os.system(f"betterlockscreen {flag} blur -t '{message}'")


@cli.script("no_args")
def lock_no_args():
    '''Locks the screen'''
    lock_anon(sleep=False)


cli()
